version: '3'
services:
  locust-master:
    image: dojot/locust:v0.5.0-alpha.2
    command: bash master_entrypoint.sh
    volumes:
      # If you need to change code while running the container, activate this volume:
      # - ..:/usr/src/app
      # If you only need to generate certificates, activate this volume instead:
      - ../cert:/usr/src/app/cert
    environment:
      DOJOT_URL: "http://127.0.0.1:8000"
      DOJOT_MQTT_HOST: "127.0.0.1"
      # TODO: differentiate DOJOT_MQTT_PORT and DOJOT_MQTTS_PORT variables
      DOJOT_MQTT_PORT: "1883"
      DOJOT_MQTT_TIMEOUT: "120"
      DOJOT_ENV: "n"

      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWD: ""
      REDIS_BACKUP: "y"
    networks:
      - default
    depends_on:
      - redis
    ports:
      - 8089:8089
      - 5557:5557
    healthcheck:
      test: curl --fail -s http://localhost:8089 || exit 1
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:5.0.5-alpine3.10
    networks:
      - default
    restart: always
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - 6380:6379
    volumes:
      - ../db/:/data
