name: V2K Bridge (connector/mqtt/vernemq/v2k-bridge)

# trigger when create a branch, push a tag or a branch, PR with changes in 'connector/mqtt/vernemq/v2k-bridge/**'
on:
  create:
  push:
  pull_request:
    paths:
      - 'connector/mqtt/vernemq/v2k-bridge/**'

jobs:
  unit-tests:
    name: (connector/mqtt/vernemq/v2k-bridge) Unit Tests #  path to help identify in Status checks each job
    if: contains(github.event.head_commit.message, 'ci skip') == false # if the commit message has ci skip, doesn't run anything because needs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        cd connector/mqtt/vernemq/v2k-bridge/
        npm ci
        npm run build --if-present
        npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: connector/mqtt/vernemq/v2k-bridge/coverage
        flags: V2KBridge # Flags allow you to isolate coverage reports for different tests
        name: v2k-bridge # Custom defined name for the upload

  docker-hub:
    needs: unit-tests
    name: (connector/mqtt/vernemq/v2k-bridge) Build and Publish image to DockerHUb #  path to help identify in Status checks each job
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/pull/') == false # if this a PR doesn't run
    steps:

    - name: Owner Repository
      id: get_owner
      run: |
        export OWNER=$(echo ${{ github.repository }} | cut -f1 -d"/")
        echo Current Owner is $OWNER
        echo ::set-output name=owner::$OWNER
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and Push
      uses: elgohr/Publish-Docker-Github-Action@2.16
      with:
        name: ${{ steps.get_owner.outputs.owner }}/v2k-bridge
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: connector/mqtt/vernemq/v2k-bridge/
        buildoptions: " --label 'commit_sha'='${{ github.sha }}' " # label with commit that built image
        tag_names: true # tag will be based in branch name or tag name
